apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

nodeGroups:
  - name: linux-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
    volumeSize: 20
    


